cc_binary(
    name="cv2_stream",
    srcs=["cv2_stream.cpp"],
    deps=["@linux_opencv//:opencv",]
)


cc_binary(
    name="cv2_raw",
    srcs=["cv2_raw.cpp"],
    deps=["@linux_opencv//:opencv",]
)
