cc_binary(
    name="opencv_raw",
    srcs=["opencv_raw.cpp"],
    deps=[
        "@dearimgui//:imgui_glfw",
        "@linux_opencv//:opencv",
        "@glfw_linux//:glfw",
        "@gles_linux//:gles",    
        "@opengl_linux//:gl",
        "@stblib//:stb_image",
        ],
)


cc_binary(
    name="opencv_vid",
    srcs=["opencv_vid.cpp"],
    deps=[
        "@dearimgui//:imgui_glfw",
        "@linux_opencv//:opencv",
        "@glfw_linux//:glfw",
        "@gles_linux//:gles",    
        "@opengl_linux//:gl",
        ],
)


